name: CI
on: [push, pull_request]
permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Go 1.24
        uses: actions/setup-go@v5
        with:
          go-version: 1.24
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.4.0

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v5
      - name: Set up Go 1.24
        uses: actions/setup-go@v5
        with:
          go-version: 1.24
      - name: Build binary
        run: go build -v ./...

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v5
      - name: Set up Go 1.24
        uses: actions/setup-go@v5
        with:
          go-version: 1.24
      - name: Run Tests
        run: go test -v ./...
